# Matrices, Part 1

In [1]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

## Exercise: Neutral Element

Define the following matrices:

$
\begin{eqnarray}
A & = &
\begin{pmatrix}
    1 & 3 & 1 \\
    3 & 2 & 5 \\
    1 & 2 & 2 \\
\end{pmatrix}
\\
I_3 & = &
\begin{pmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 \\
\end{pmatrix}
\end{eqnarray}
$

In [44]:
A = np.array( [
        [1.,3,1], 
        [3,2,5],
        [2,2,2]
    ] )

print(A)

[[1. 3. 1.]
 [3. 2. 5.]
 [2. 2. 2.]]


In [55]:
# I3 = 

### Multiply the matrices  $A$ and $I_3$.

To perform a matrix-matrix-multiplication or a matrix-vector-multiplication you have to use the dot product.

**There are two ways to call the dot product function:** <br>
1. Call the dot product function which is already a matrix method, i.e. `A.dot(B)`.
1. Call the numpy function `dot()`, i.e. `np.dot(A,B)`

Calculate $A\cdot I_3$ and $I_3 \cdot A$.

In [78]:
# A*I3
A2 = A.dot(I3)    # option 1
A3 = np.dot(A,I3) # option 2

In [79]:
# I3*A
A4 = I3.dot(A)    # option 1
A5 = np.dot(I3,A) # option 2

**Compare** $A$, $A_2$, $A_3$, $A_4$, $A_5$

In [81]:
print(f"A = \n {A}")
print(f"A2 = \n {A2}")
print("...")
# print ...

A = 
 [[1. 3. 1.]
 [3. 2. 5.]
 [2. 2. 2.]]
A2 = 
 [[1. 3. 1.]
 [3. 2. 5.]
 [2. 2. 2.]]
...


Observation: $A\cdot I = I\cdot A = A$.

Multiplication with $I$ does not change the matrix $A$. <br> 
$I$ is called the unit matrix or the identity matrix. It acts like the $1$ in a scalar multiplication. <br>
$I$ is is the **neutral element of multipliction**. It is sometimes denoted as 
$
\mathbb{1}
$.

There is a short numpy function to generate any n-dimensional unit matrix:

In [73]:
# create a 5x5 unit matrix
n = 5
I5 = np.eye(n)
print(I5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Exercise: Matrix multiplications are **generally** not commutative! (There are exeptions ...)



In [75]:
K = np.array([[1., 2,  3], [4, 5, 6], [7, 8, 9]])
print(K)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Calculate $A\cdot K$ and $K\cdot A$. What do you observe?

In [ ]:
# A.dot(...)
# ...

## Exercise: Inverse Element 


Let us discuss the scalar ("ordinary") multiplication first (with real numbers). The element $1$ is the neutral element of the scalar multiplication: 
<br>
$x\cdot 1 = 1\cdot x = x$.

The inverse element is the element the multiplication with which yields the neutral element. 

If $x\cdot y = y\cdot x = 1$ is defined, then $y$ is the inverse element to $x$. 

The inverse element is denoted as $ y = x^{-1}$, i.e. $x\cdot x^{-1} = x^{-1} \cdot x = 1 $ 

In scalar multiplication: $x^{-1} = \frac{1}{x}$, since $\frac{1}{x}\cdot x = \frac{x}{x} = 1$. 

This only works for $x \ne 0$: There is no to inverse element $y$ of $0$, such that $0\cdot y = 1$.

**The concept of neutral and inverse elements can be transferred to matrices!**

Let us assume the multiplication of two **square matrices** yields the neutral element, i.e. $X\cdot Y = \mathbb{1}$. 
<br>
Then the matrix $Y$ is called the inverse of $X$: 
<br>
$Y = X^{-1}$.  

The multiplication with the inverse element is commutative, i.e. 
<br>
$X\cdot X^{-1} = X^{-1} \cdot X = \mathbb{1}$. 

### Some practical calculations

Define the following matrices:

$
\begin{eqnarray}
A & = &
\begin{pmatrix}
    1 & 3 & 1 \\
    3 & 2 & 5 \\
    1 & 2 & 2 \\
\end{pmatrix}
\\
B & = &
\begin{pmatrix}
    -6 & -4 & 13 \\
    4 & 0 & -2 \\
    2 & 4 & -7 \\
\end{pmatrix}
\\
C & = & \frac{1}{8} B 
\end{eqnarray}
$


In [103]:
B = np.array([[-6., -4,  13], [4, 0, -2], [2,4,-7]])
print(B)

[[-6. -4. 13.]
 [ 4.  0. -2.]
 [ 2.  4. -7.]]


In [104]:
# C = ...
print(C)

[[-0.75  -0.5    1.625]
 [ 0.5    0.    -0.25 ]
 [ 0.25   0.5   -0.875]]


Multiply the matrices: $D = A\cdot B$.

In [105]:
# Call:
# D = A.dot(B)
print(D)

NameError: name 'D' is not defined

Multiply the matrices: $J = A\cdot C$. <br>
What do you observe?

In [106]:
# Perform J = A dot C ...
#  J = 
print(J)

NameError: name 'J' is not defined

How are $A$ and $C$ related?

## Exercise: A square matrix is invertible if and only if its determinant is not 0.

We have seen that $A$ is invertible with $A^{-1} = C$.

Let us check if determinants are non-zero:

$d_A = \det{(A)}$ and $d_C = \det{(C)}$ 

Search the numpy documentation for help on $\det(\ldots)$: https://numpy.org/doc/stable/reference/routines.linalg.html

In [107]:
# Calce determinants ...
# dA = ...
# ...

print(f"det(A)        = {dA:6.4f}")
print(f"det(C)        = {dC:6.4f}")
print(f"det(A)*det(C) = {dA*dC:6.4f}")


det(A)        = 8.0000
det(C)        = 0.1250
det(A)*det(C) = 1.0000


What do you observe?

**Example of a non-invertible matrix**

In [113]:
F = np.array([[1,2,3],[2,4,6],[7,8,9]])
print(F)

[[1 2 3]
 [2 4 6]
 [7 8 9]]


Determine $\det(F)$. What does the result indicate?

In [114]:
# dF = ...
print(dF)

NameError: name 'dF' is not defined

### Exercise: Invert matrices

The command to matrix $A$ is `Ainv = numpy.linalg.inv(A)`

`numpy.linalg` was imported earlier as `la`.

In [119]:
Ainv = la.inv(A)
print(Ainv)

[[-7.50000000e-01 -5.00000000e-01  1.62500000e+00]
 [ 5.00000000e-01  7.93016446e-18 -2.50000000e-01]
 [ 2.50000000e-01  5.00000000e-01 -8.75000000e-01]]


How can you check that this is really the inverse $A^{-1}$?

**Invert the matrix G:**

In [145]:
G = np.array([[1., 2, 3],
              [2, 4, 6],
              [1, 6, 7]])
print(G)

[[1. 2. 3.]
 [2. 4. 6.]
 [1. 6. 7.]]


**Invert the matrix R:**

$
\begin{eqnarray}
R & = &
\begin{pmatrix}
    \cos(\phi) & -\sin(\phi) & 0 \\
    \sin(\phi) & \cos(\phi) & 0 \\
    0 & 0 & 1 \\
\end{pmatrix}
\end{eqnarray}
$

with an angle $\phi$.

Use $\phi = 30°$.

In [158]:
phi = np.deg2rad(30) # angle, degree to radian

In [159]:
R = np.array([
    [np.cos(phi), -np.sin(phi),  0],
    [np.sin(phi),  np.cos(phi),  0],
    [          0,            0,  1]    
])
print(R)

[[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]


Determine the determinant and invert the matrix. Check whether $R\cdot R^{-1} = \mathbb{1}$.